#
# $Id: Makefile,v 1.1.1.1 2000/08/14 18:46:13 labovit Exp $
#

include ../../Make.include

OBJS    = rip_proto.o rip2.o ripng.o
ARCHIVE = $(RIPLIB)

include ../Make.include

# DO NOT DELETE THIS LINE -- make depend depends on it.
