#
# $Id: Makefile,v 1.1.1.1 2000/08/14 18:46:12 labovit Exp $
#

include ../../Make.include

OBJS   = dvmrp.o pim.o cache.o
ARCHIVE = $(PIMLIB)

include ../Make.include

# DO NOT DELETE THIS LINE -- make depend depends on it.
