#
# $Id: Makefile,v 1.1.1.1 2000/08/14 18:46:13 labovit Exp $
#

include ../../Make.include

OBJS    = rib.o rib_uii.o
ARCHIVE = $(RIBLIB)

include ../Make.include

#all:	$(OBJS)
#	ld -o librib.s0.1.1 -G *.o
#	$(CP) ./librib.so /usr/lib/

# DO NOT DELETE THIS LINE -- make depend depends on it.
