#
# $Id: Makefile,v 1.1.1.1 2000/08/14 18:46:11 labovit Exp $
#

include ../../Make.include

OBJS    = util.o prefix.o route_util.o gateway.o mrt.o user.o schedule.o \
	  alist.o trace.o select.o connect.o reboot.o user_old.o user_util.o \
	  compat.o vars.o nexthop.o buffer.o hashfn.o
#ipv6.o error.o
ARCHIVE = $(MRTLIB)

include ../Make.include

# DO NOT DELETE THIS LINE -- make depend depends on it.
