#
# $Id: Makefile,v 1.1.1.1 2000/08/14 18:46:10 labovit Exp $
#

include ../../Make.include

OBJS    = bgp_util.o bgp_sm.o bgp_pdu.o view.o bgp_timer.o bgp_thread.o \
	  bgp_dump.o bgp_dump2.o
ARCHIVE = $(BGPLIB)

include ../Make.include

# DO NOT DELETE THIS LINE -- make depend depends on it.
