#
# $Id: Makefile,v 1.1.1.1 2000/08/14 18:46:11 labovit Exp $
#

include ../../Make.include

OBJS    = filter.o
ARCHIVE = $(BGPLIB)

include ../Make.include

# DO NOT DELETE THIS LINE -- make depend depends on it.
