#
# $Id: Makefile,v 1.1.1.1 2000/08/14 18:46:13 labovit Exp $
#

include ../../Make.include

OBJS    = port_serv_lib.o
ARCHIVE = $(MRTLIB)

nothing:

include ../Make.include

# DO NOT DELETE THIS LINE -- make depend depends on it.
