#
# $Id: Makefile,v 1.1.1.1 2000/08/14 18:46:11 labovit Exp $
#

include ../../Make.include

OBJS    = config_file.o commconf.o bgpconf.o rtmapconf.o load.o ripconf.o \
	  multiconf.o dvmrpconf.o pimconf.o
ARCHIVE = $(CFGLIB)

include ../Make.include

# DO NOT DELETE THIS LINE -- make depend depends on it.
